"use client";
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import React from 'react';

const STATUS_COLORS = {
  OK: "#16a34a",
  Standby: "#facc15",
  FAULT: "#dc2626",
  "NOT WORKING": "#b91c1c",
  OFF: "#6b7280",
  "Under Maintenance": "#f97316",
  "Needs Repair": "#ec4899",
  Testing: "#60a5fa",
  "Awaiting Parts": "#a855f7",
  Calibrating: "#4f46e5",
  "Out of Service": "#000000",
  "Cube-A": "#14b8a6",
  "Cube-B": "#06b6d4",
  "Cube-C": "#84cc16",
  "Cube-D": "#f59e0b",
};

const styles = StyleSheet.create({
  page: { padding: 20, fontSize: 10 },
  header: { textAlign: 'center', marginBottom: 10, fontSize: 14, fontWeight: 'bold' },
  table: { display: 'table', width: 'auto', borderStyle: 'solid', borderWidth: 1, borderColor: '#bdbdbd' },
  tableRow: { flexDirection: 'row', minHeight: 20 },
  tableCol: { borderStyle: 'solid', borderWidth: 1, borderColor: '#bdbdbd', padding: 3, flexGrow: 1 },
  tableCell: { fontSize: 8, wordWrap: 'wrap' },
  statusCell: (status) => ({
    backgroundColor: STATUS_COLORS[status] || '#d1d5db',
    color: '#fff',
    padding: 2,
    fontSize: 8,
    textAlign: 'center',
    flexGrow: 1,
  }),
});

export const StudioPDFDocument = ({ studios, user, currentDateTime }) => {
  // Determine all keys used in data to create consistent column order
  const allKeys = Array.from(new Set(studios.flatMap(s => Object.keys(s))));

  return (
    <Document>
      <Page size="A4" orientation="landscape" style={styles.page}>
        <Text style={styles.header}>Noida Studio Displays Checklist</Text>
        <Text style={{ textAlign: 'center', marginBottom: 10 }}>
          Generated by: {user.name} ({user.email}) | {currentDateTime}
        </Text>

        <View style={styles.table}>
          {/* Header Row */}
          <View style={styles.tableRow}>
            {allKeys.map((key) => (
              <View key={key} style={styles.tableCol}>
                <Text style={[styles.tableCell, { fontWeight: 'bold' }]}>{key.toUpperCase()}</Text>
              </View>
            ))}
          </View>

          {/* Data Rows */}
          {studios.map((s, idx) => (
            <View key={idx} style={styles.tableRow}>
              {allKeys.map((key) => {
                const val = s[key] ?? '';
                return (
                  <View
                    key={key}
                    style={key === 'status' ? styles.statusCell(val) : styles.tableCol}
                  >
                    <Text style={styles.tableCell}>{val}</Text>
                  </View>
                );
              })}
            </View>
          ))}
        </View>
      </Page>
    </Document>
  );
};
