import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const formatDate = (date) => {
  if (!date) return '-';
  const d = new Date(date);
  const day = String(d.getDate()).padStart(2, '0');
  const month = String(d.getMonth() + 1).padStart(2, '0'); // months are 0-indexed
  const year = d.getFullYear();
  return `${day}-${month}-${year}`;
};
export const generatePDF = async ({
  eventName,
  date,
  channel,
  broadcastType,
  location,
  city,
  setupType = [],
  showType,
  camera,
  jimmyJib,
  livePlatform = [],
  setupDate,
  setupStartTime,
  setupEndTime,
  checkingDone,
  eventEngineer = [],
  showProducer,
  showDop,
  onlineEditor,
  electrical,
  soundEngineer,
  productionControl,
  equipment = [],
  liveSource = [],
  power = [],
  loggedInUser,
  userFullName,
  userEmail,
  createdBy,
  days = [] // <- dynamic array of day objects
})=> {
  try {
	  console.log(power);
    if (!eventName || !date || !channel || !broadcastType) {
    throw new Error("PDF GENRATION FAILED, MAKE SURE TO ADD REQUIRED FIELDS");

    }
    if (eventEngineer.length === 0) {
      return;
    }

const now = new Date();
const pad = (n) => String(n).padStart(2, '0');

const fileTimestamp = `${now.getFullYear()}${pad(now.getMonth()+1)}${pad(now.getDate())}_${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`;
const displayTimestamp = `${pad(now.getDate())}-${pad(now.getMonth()+1)}-${now.getFullYear()} ${pad(now.getHours())}:${pad(now.getMinutes())}:${pad(now.getSeconds())}`;

    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a3',compress: true });
    
    doc.setProperties({
      title: `Network18 Event Report - ${eventName}`,
      author: `${userFullName} (${loggedInUser})`,
      subject: 'Event Report',
      keywords: 'event, report, network18',
      creator: `Network18 Event Report System - Generated by ${loggedInUser}`
    });

      const margin = 6;
      let y = 12;
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const usableWidth = pageWidth - (margin * 2);
      const lineHeight = 4.5;

      

      // Logo loading function
      const loadImage = (url) => {
        return new Promise((resolve, reject) => {
          const img = new Image();
          img.crossOrigin = 'Anonymous';
          img.onload = () => {
            console.log('Image loaded successfully:', url);
            resolve(img);
          };
          img.onerror = (e) => {
            console.error('Failed to load image:', url, e);
            reject(new Error(`Failed to load image at ${url}: ${e.message}`));
          };
          img.src = url;
        });
      };

      // Try to load logo from public folder
      try {
        const img = await loadImage('/NW18.png');
        const imgWidth = 25;
        const imgHeight = (img.height * imgWidth) / img.width;
        doc.addImage(img, 'PNG', margin, y - 8, imgWidth, imgHeight);
      } catch (error) {
        console.warn('Logo loading failed, using text fallback:', error.message);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(10);
        doc.setTextColor(0, 51, 102);
        doc.text('NETWORK18', margin, y);
      }

      // Enhanced Main header
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(16);
      doc.setTextColor(0, 51, 102);
      const headerText = 'Network18 Event Report';
      const headerWidth = doc.getTextWidth(headerText);
      const headerX = (pageWidth - headerWidth) / 2;
      doc.text(headerText, headerX, y);
      y += 8;

      // Enhanced Timestamp with user information
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 100, 100);
      const timestampText = `Generated: ${displayTimestamp} | By: ${userFullName} (${loggedInUser})`;
      const timestampWidth = doc.getTextWidth(timestampText);
      const timestampX = (pageWidth - timestampWidth) / 2;
      doc.text(timestampText, timestampX, y);
      y += 6;

      // ADD USER STAMP BOX (NEW SECTION)
      doc.setFillColor(240, 248, 255); // Light blue background
      doc.rect(margin, y, usableWidth, 12, 'F');
      doc.setDrawColor(0, 51, 102);
      doc.rect(margin, y, usableWidth, 12, 'S');
      
      y += 3;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(0, 51, 102);
      doc.text('Report Generated By:', margin + 3, y);
      
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(0, 0, 0);
      doc.text(`${userFullName} (${loggedInUser})`, margin + 40, y);
      
      if (userEmail) {
        doc.text(`Email: ${userEmail}`, margin + 3, y + 4);
      }
      
      
      
      
      y += 12;

      // Day and Created By
      doc.setFontSize(7);
      doc.setTextColor(0, 0, 0);
      
      if (createdBy) {
        const createdByText = `Created By: ${createdBy}`;
        const textWidth = doc.getTextWidth(createdByText);
        doc.text(createdByText, pageWidth - margin - textWidth, y);
      }
      y += 8;

      // Section header function
      const addSectionHeader = (title, x, y, width) => {
        doc.setFillColor(0, 51, 102);
        doc.rect(x, y - 3, width, 6, 'F');
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(9);
        doc.setTextColor(255, 255, 255);
        doc.text(title, x + 2, y + 1);
        doc.setTextColor(0, 0, 0);
        return y + 6;
      };

      // Two-column layout with better spacing
      const leftColWidth = usableWidth * 0.46; 
      const rightColWidth = usableWidth * 0.46; 
      const colGap = usableWidth * 0.08; 
      const leftX = margin;
      const rightX = margin + leftColWidth + colGap;
      let leftY = y;
      let rightY = y;

      // Left Column - Event Details
      leftY = addSectionHeader('Event Details', leftX, leftY, leftColWidth);
      doc.setFontSize(8);
      doc.setTextColor(0, 0, 0);
      
      const eventDetails = [
        { label: 'Event Name:', value: eventName || '-' },
        { label: 'Date:', value: formatDate(date) || '-' },
        { label: 'Channel:', value: channel || '-' },
        { label: 'Location:', value: location || '-' },
        { label: 'City:', value: city || '-' },
        { label: 'Setup Type:', value: setupType|| '-' },
        { label: 'Show Type:', value: showType || '-' },
        { label: 'Camera:', value: camera || '-' },
        { label: 'Jimmy Jib:', value: jimmyJib || '-' },
        { label: 'Broadcast:', value: broadcastType || '-' },
        { label: 'Live Platform:', value: broadcastType === 'Live' ? livePlatform.join(', ') || '-' : '-' }
      ];
      
      eventDetails.forEach(detail => {
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0, 51, 102);
        doc.text(detail.label, leftX, leftY);
        
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(0, 0, 0);
        const labelWidth = doc.getTextWidth(detail.label) + 3;
        doc.text(detail.value, leftX + labelWidth, leftY);
        
        leftY += lineHeight;
      });
      leftY += 3;

      // Setup & Timing
      leftY = addSectionHeader('Setup & Timing', leftX, leftY, leftColWidth);
      doc.setFontSize(8);
      const setupDetails = [
        { label: 'Setup Date:', value: formatDate(setupDate) || '-' },
        { label: 'Start Time:', value: setupStartTime || '-' },
        { label: 'End Time:', value: setupEndTime || '-' },
        { label: 'Checking Done:', value: checkingDone || '-' }
      ];
      
      setupDetails.forEach(detail => {
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0, 51, 102);
        doc.text(detail.label, leftX, leftY);
        
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(0, 0, 0);
        const labelWidth = doc.getTextWidth(detail.label) + 3;
        doc.text(detail.value, leftX + labelWidth, leftY);
        
        leftY += lineHeight;
      });
      leftY += 3;

      

      // Right Column - Team Details
      rightY = addSectionHeader('Team Details', rightX, rightY, rightColWidth);
      doc.setFontSize(8);
      const teamDetails = [
        { label: 'Event Engineer:', value: eventEngineer || '-' },
        { label: 'Show Producer:', value: showProducer || '-' },
        { label: 'Show DOP:', value: showDop || '-' },
        { label: 'Online Editor:', value: onlineEditor || '-' },
        { label: 'Electrical:', value: electrical || '-' },
        { label: 'Sound Engineer:', value: soundEngineer || '-' },
        { label: 'Production Control:', value: productionControl || '-' }
      ];
      
      teamDetails.forEach(detail => {
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0, 51, 102);
        doc.text(detail.label, rightX, rightY);
        
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(0, 0, 0);
        const labelWidth = doc.getTextWidth(detail.label) + 3;
        doc.text(detail.value, rightX + labelWidth, rightY);
        
        rightY += lineHeight;
      });

      // Equipment section - Full width
      const equipmentY = Math.max(leftY, rightY) + 5;
      let currentY = addSectionHeader('Equipment', margin, equipmentY, usableWidth);

      // Equipment table
      const hasHiredEquipment = equipment.some(item => item.hired);
      const equipmentHeaders = hasHiredEquipment
        ? ['#', 'Equipment', 'Model', 'Qty', 'Install', 'Done', 'In-House', 'Hired', 'Vendor', 'Remarks', 'Status']
        : ['#', 'Equipment', 'Model', 'Qty', 'Install', 'Done', 'In-House', 'Remarks', 'Status'];

      const equipmentData = equipment.map((item, index) => {
        const baseRow = [
          index + 1,
          item.equipment || '',
          item.modelNo || '',
          item.qty || '',
          item.installationTime || '',
          item.doneTime || '',
          item.inHouse ? 'Yes' : '',
          item.remarks || '',
          item.status || '',
        ];
        if (hasHiredEquipment) {
          baseRow.splice(7, 0, item.hired ? 'Yes' : '');
          baseRow.splice(8, 0, item.hired ? item.vendorName || '' : '');
        }
        return baseRow;
      });

      if (equipmentData.length > 0) {
        autoTable(doc, {
		  startY: currentY,
		  head: [equipmentHeaders],
		  body: equipmentData,
          theme: 'grid',
          styles: {
            fontSize: 6.5,
            cellPadding: 0.5,
            textColor: [0, 0, 0],
            halign: 'left',
            valign: 'middle',
            overflow: 'linebreak',
            lineWidth: 0.1,
          },
          headStyles: {
            fillColor: [0, 51, 102],
            textColor: [255, 255, 255],
            halign: 'center',
            fontSize: 6.5,
            cellPadding: 0.5,
            fontStyle: 'bold',
          },
          alternateRowStyles: {
            fillColor: [245, 245, 245],
          },
          margin: { left: margin, right: margin },
          tableWidth: 'auto',
        });
        currentY = doc.lastAutoTable.finalY + 2;
      }

      // Live Source section
      currentY = addSectionHeader('Live Source', margin, currentY + 3, usableWidth);
      autoTable(doc, {
  
        startY: currentY,
        head: [['#', 'Name', 'Avail', 'Type', 'BW', 'Note', 'Status']],
        body: liveSource.map((item, index) => [
          index + 1,
          item.name || '',
          item.available === 'Yes' ? 'Yes' : item.available === 'No' ? 'No' : '',
          item.type ||  '',
          item.bandwidth +"/mbps" || '',
          item.note || '',
          item.status || '',
        ]),
        theme: 'grid',
        styles: {
          fontSize: 6.5,
          cellPadding: 0.5,
          textColor: [0, 0, 0],
          halign: 'left',
          valign: 'middle',
          lineWidth: 0.1,
        },
        headStyles: {
          fillColor: [0, 51, 102],
          textColor: [255, 255, 255],
          halign: 'center',
          fontSize: 6.5,
          cellPadding: 0.5,
          fontStyle: 'bold',
        },
        alternateRowStyles: {
          fillColor: [245, 245, 245],
        },
        margin: { left: margin, right: margin },
        tableWidth: 'auto',
      });
      currentY = doc.lastAutoTable.finalY + 2;

      // Power Source section
      currentY = addSectionHeader('Power Source', margin, currentY + 3, usableWidth);
      autoTable(doc, {
  
        startY: currentY,
        head: [['#', 'Source', 'Avail', 'kVA', 'Value', 'Note', 'Status']],
        body: power.map((item, index) => [
          index + 1,
          item.source || '',
          item.available || '',
          item.kva || '',
          item.value || '',
          item.note || '',
          item.status || '',
        ]),
        theme: 'grid',
        styles: {
          fontSize: 6.5,
          cellPadding: 0.5,
          textColor: [0, 0, 0],
          halign: 'left',
          valign: 'middle',
          lineWidth: 0.1,
        },
        headStyles: {
          fillColor: [0, 51, 102],
          textColor: [255, 255, 255],
          halign: 'center',
          fontSize: 6.5,
          cellPadding: 0.5,
          fontStyle: 'bold',
        },
        alternateRowStyles: {
          fillColor: [245, 245, 245],
        },
        margin: { left: margin, right: margin },
        tableWidth: 'auto',
      });
      currentY = doc.lastAutoTable.finalY + 2;


// DAYS HANDLING (dynamic)
if (Array.isArray(days) && days.length > 0) {
	console.log("MAKING");
  for (let i = 0; i < days.length; i++) {
    const day = days[i];
    const dayNumber = i + 1;

    currentY = addSectionHeader(`Day ${dayNumber} Details`, margin, currentY + 3, usableWidth);

    const dayDetails = [
      { label: 'Date:', value: formatDate(day.date) },
      { label: 'Checking Done:', value: day.checkingDone },
      { label: 'Feed Test Location:', value: day.feedTestLocation },
      { label: 'Feed Test Date:', value: formatDate(day.feedTestDate) },
      { label: 'Feed Test Time:', value: day.feedTestTime },
      { label: 'Start Time:', value: day.eventStartTime },
      { label: 'End Time:', value: day.eventEndTime },
      { label: 'Duration:', value: day.eventDuration },
    ];

    doc.setFontSize(8);

    // Print day details in two columns
    dayDetails.forEach((item, index) => {
      const col = index % 2 === 0 ? margin : margin + 100;
      const row = Math.floor(index / 2);

      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0, 51, 102);
      doc.text(item.label, col, currentY + row * 4.5);

      doc.setFont('helvetica', 'normal');
      doc.setTextColor(0, 0, 0);
      const labelWidth = doc.getTextWidth(item.label) + 3;
      doc.text(item.value || '-', col + labelWidth, currentY + row * 4.5);
    });
    currentY += Math.ceil(dayDetails.length / 2) * 4.5 + 2;

    // Comments & Signature
	if (day.comments) {
	  const colorMap = {
		Red: [255, 0, 0],
		Black: [0, 0, 0],
		Blue: [0, 0, 255],
		Green: [0, 128, 0],
	  };

	  // support both array [r,g,b] and string "Red"
	  let commentColor = [0, 0, 0]; // default black
	  if (Array.isArray(day.dayCommentColor)) {
		commentColor = day.dayCommentColor;
	  } else if (typeof day.dayCommentColor === "string" && colorMap[day.dayCommentColor]) {
		commentColor = colorMap[day.dayCommentColor];
	  }

	  doc.setFont('helvetica', 'bold');
	  doc.setTextColor(0, 51, 102);
	  doc.text('Comments:', margin, currentY);

	  const commentsText = doc.splitTextToSize(day.comments, usableWidth - 25);
	  doc.setFont('helvetica', 'normal');
	  doc.setFontSize(8);

	  doc.setTextColor(commentColor[0], commentColor[1], commentColor[2]);
	  doc.text(commentsText, margin + 25, currentY);

	  currentY += commentsText.length * 4 + 2;
	  doc.setTextColor(0, 0, 0);
	}

    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 51, 102);
    doc.text('Signature:', margin, currentY);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);
    const sigWidth = doc.getTextWidth('Signature:') + 3;
    doc.text(`${day.signature || '_________________________'}`, margin + sigWidth, currentY);

    const dateXPos = margin + 160;
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 51, 102);
    doc.text('Date:', dateXPos, currentY);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);
    const dateWidth = doc.getTextWidth('Date:') + 3;
    doc.text(`${formatDate(day.signatureDate) || '_____________'}`, dateXPos + dateWidth, currentY);
    currentY += 5;
  }
}
     

      

     

      // Enhanced footer with user information
      const footerY = pageHeight - 12;
      doc.setFontSize(7);
      doc.setTextColor(150, 150, 150);
      
      const footerText = `Network18 Event Report System - Generated by ${loggedInUser} - ${displayTimestamp}`;
      const footerWidth = doc.getTextWidth(footerText);
      doc.text(footerText, (pageWidth - footerWidth) / 2, footerY);
      
      // Additional user stamp line
      const userStampText = `Confidential - Authorized by ${userFullName}`;
      const userStampWidth = doc.getTextWidth(userStampText);
      doc.text(userStampText, (pageWidth - userStampWidth) / 2, footerY + 4);


    const cleanEventName = (eventName || 'Event').replace(/[^a-zA-Z0-9\s]/g, '').replace(/\s+/g, '_');
    const filename = `Network18_Event_Report_${cleanEventName}_${loggedInUser}_${fileTimestamp}.pdf`;
    doc.save(filename);

    return filename;
  } catch (error) {
    console.error('PDF generation error:', error);
    throw new Error("PDF GENRATION FAILED, MAKE SURE TO ADD REQUIRED FIELDS");
  }
};
